name: widgets_demo
description: "Espace de présentation des Widgets du Design System Listo."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  cupertino_icons: ^1.0.8
  widgetbook: ^3.7.1
  google_fonts: ^6.2.1
  url_launcher: ^6.2.6
  url_launcher_web: ^2.3.1
  flutter_markdown: ^0.7.1
  listo_design_system:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/markdown/
